# Generated by Django 5.0.3 on 2024-05-28 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filesync",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Synced files"},
        ),
    ]
